"""
  Configuracoes gerais do sistema

  Em vias de facilitar alteracoes, este arquivo centraliza todas as informacoes que 
  sao constantes pelo codigo.
"""

# QUANTIDADE DE INTEGRACOES POR PASSO
SIMULACAO_QNTD_INTEGRACOES_PASSO = 100

# DISTANCIA MINIMA PARA COLISAO
DIST_MIN_COLISAO = 1

# RANGE DE EXIBICAO DOS GRAFICOS
RANGE_PLOT_X = [-2,2 ]
RANGE_PLOT_Y = [-2,2 ]
RANGE_PLOT_Z = [-2,2 ]

# INTERVALO DE PLOT DAS ANIMACOES
ANIMACAO_INTERVALO = 10

# DPI DAS ANIMACOES
ANIMACAO_DPI = 100

# TAMANHO DE RASTRO NAS ANIMACOES
TAMANHO_RASTRO_ANIMACOES = 100

# QUANTIDADE DE PONTOS GUARDADOS ANTES DE SALVAR
SIMULACAO_QNTD_SALVAR = 100

# SEPARADOR DOS ARQUIVOS
SEPARADOR_ARQUIVOS = "\n##########\n"